server:
  port: 9002

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.128:1111
  application:
    name: nacos-payment-provider

management:
  endpoints:
    web:
      exposure:
        include: "*"